version: 2

models:
  - name: stg_sales__buying_groups
    description: Staged buying group data from wwi sales.
    columns:
      - name: buying_group_id
        description: The primary key for buying_groups.
        tests:
          - unique
          - not_null
      - name: buying_group_name
        description: Buying group name.
        tests:
          - not_null

  - name: stg_sales__customer_categories
    description: Staged customer category data from wwi sales.
    columns:
      - name: customer_category_id
        description: The primary key for customer_categories.
        tests:
          - unique
          - not_null
      - name: customer_category_name
        description: Customer category name.
        tests:
          - not_null

  - name: stg_sales__customers
    description: Staged customer data from wwi sales.
    columns:
      - name: customer_id
        description: The primary key for custommers.
        tests:
          - unique
          - not_null
      - name: customer_category_id
        description: The foreign key for customers and customer_categories.
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales__customer_categories')
              field: customer_category_id
      - name: buying_group_id
        description: The foreign key for customers and buying_groups.
        tests:
          - relationships:
              to: ref('stg_sales__buying_groups')
              field: buying_group_id
      - name: delivery_city_id
        description: The foreign key for customer and cities (application).
        tests:
          - not_null
          - relationships:
              to: ref('stg_application__cities')
              field: city_id
      - name: customer_name
        description: Customer name.
        tests:
          - not_null
      - name: account_opened_date
        description: Customer account open date.
        tests:
          - not_null
      - name: phone_number
        description: Customer phone.
      - name: fax_number
        description: Customer fax.
      - name: website_url
        description: Customer website.

  - name: stg_sales__invoice_lines
    description: Staged invoice line data from wwi sales.
    columns:
      - name: invoice_line_id
        description: The primary key for invoice lines.
        tests:
          - unique
          - not_null
      - name: invoice_id
        description: The foreign key for invoice lines and invoices.
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales__invoices')
              field: invoice_id
      - name: stock_item_id
        description: The foreign key for invoice lines and stock_items (wareshoue).
        tests:
          - not_null
          - relationships:
              to: ref('stg_warehouse__stock_items')
              field: stock_item_id
      - name: package_type_id
        description: The foreign key for invoice lines and package_types (wareshoue).
        tests:
          - not_null
          - relationships:
              to: ref('stg_warehouse__package_types')
              field: package_type_id
      - name: quantity
        description: Amount stock in order.
        tests:
          - not_null
      - name: unit_price
        description: Each stock unit price.
        tests:
          - not_null
      - name: tax_rate
        description: Each stock tax rate.
        tests:
          - not_null
      - name: tax_amount
        description: Each stock tax amount.
        tests:
          - not_null
      - name: line_profix
        description: Each stock profix.
        tests:
          - not_null
      - name: extended_price
        description: Each stock extended price.
        tests:
          - not_null

  - name: stg_sales__invoices
    description: Staged invoice data from wwi sales.
    columns:
      - name: invoice_id
        description: The primary key for invoices.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: The foreign key for invoices and customers.
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales__customers')
              field: customer_id
      - name: delivery_method_id
        description: The foreign key for invoices and delivery_methods (application).
        tests:
          - not_null
          - relationships:
              to: ref('stg_application__delivery_methods')
              field: delivery_method_id
      - name: sales_person_id
        description: The foreign key for invoices and person (application).
        tests:
          - not_null
          - relationships:
              to: ref('stg_application__person')
              field: person_id
      - name: invoice_date
        description: Invoice created date.
        tests:
          - not_null
  
  - name: stg_sales__promotion
    description: Staged promation data from wwi sales.
    columns:
      - name: promotion_id
        description: The primary key for promotion.
        tests:
          - unique
          - not_null
      - name: buying_group_id
        description: The foreign key for promotion and buying_groups.
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales__buying_groups')
              field: buying_group_id
      - name: promotion_desctiption
        description: Promotion details.
      - name: start_date
        description: Promotion start date.
        tests:
          - not_null
      - name: end_date
        description: Promotion end date.
        tests:
          - not_null
      - name: discount_amount
        description: Amount discount price.
      - name: discount_percentage
        description: Percentage discount price.
