version: 2

models:
  - name: dim_customer
    description: Customer dimension data cleaned from staging.
    columns:
      - name: customer_key
        description: The primary key for dim_customer.
        tests:
          - unique
          - not_null
      - name: customer_name
        description: Customer name.
        tests:
          - not_null
      - name: customer_category_name
        description: Customer category name.
      - name: buying_group_name
        description: Buying group name.
      - name: open_date_key
        description: Open date account.
        tests:
          - not_null
      - name: phone_number
        description: Customer phone number.
      - name: fax_number
        description: Customer fax number.
      - name: website_url
        description: Customer website.
      - name: delivery_city
        description: Customer delivery city.
      - name: delivery_state_province
        description: Customer delivery province.
      - name: delivery_country
        description: Customer delivery country.

  - name: dim_delivery_method
    description: Delivery method dimension data cleaned from staging.
    columns:
      - name: delivery_method_key
        description: The primary key for dim_delivery_method.
        tests:
          - unique
          - not_null
      - name: delivery_method_name
        description: Delivery method name.
        tests:
          - not_null
  - name: dim_product
    description: Product dimension data cleaned from staging.
    columns:
      - name: product_key
        description: The primary key for dim_product.
        tests:
          - unique
          - not_null
      - name: product_name
        description: Product name.
        tests:
          - not_null
      - name: supplier_name
        description: Supplier name.
        tests:
          - not_null
      - name: color_name
        description: Color name.
        tests:
          - not_null
      - name: package_type_name
        description: Package type name.
        tests:
          - not_null
      - name: brand
        description: Brand.
      - name: size
        description: Size.
      - name: barcode
        description: Barcode.
      - name: tax_rate
        description: Tax rate.
        tests:
          - not_null
      - name: unit_price
        description: Unit price.
        tests:
          - not_null
      - name: recommended_retail_price
        description: Recommended retail price.
        tests:
          - not_null
      - name: typical_weight_per_unit
        description: Typical weight per unit.
      - name: quantity_per_outer
        description: Quantity per order.
      - name: manufacturer
        description: Manufacturer.
        tests:
          - not_null
      - name: tags
        description: Tags.

  - name: dim_promotion
    description: Promotion dimension data cleaned from staging.
    columns:
      - name: promotion_key
        description: The primary key for dim_promotion.
        tests:
          - unique
          - not_null
      - name: promotion_description
        description: Description.
      - name: start_date
        description: Event started date.
        tests:
          - not_null
      - name: end_date
        description: Event ended date.
        tests:
          - not_null
      - name: discount_amount
        description: Discount price amount.
      - name: discount_percentage
        description: Discount price percentage.

  - name: dim_sales_person
    description: Sales person dimension data cleaned from staging.
    columns:
      - name: sales_person_key
        description: The primary key for dime_sales_person.
        tests:
          - unique
          - not_null
      - name: full_name
        description: Fullname.
        tests:
          - not_null
      - name: preferred_name
        description: Preferred name.
      - name: search_name
        description: Search name.
      - name: is_system_user
        description: Whether person is user system.
      - name: is_employee
        description: Whether person is employee.
      - name: phone_number
        description: Phone number.
      - name: fax_number
        description: Fax number.
      - name: email_address
        description: Email.

  - name: fct_sales
    description: Sales fact data cleaned from staging.
    columns:
      - name: invoice_key
        description: The primary key for fct_sales.
        tests:
          - not_null
      - name: customer_key
        description: The foreign key for fct_sales and dim_customers.
      - name: product_key
        description: The foreign key for fct_sales and dim_product.
      - name: delivery_method_key
        description: The foreign key for fct_sales and dim_delivery_methods.
      - name: sales_person_key
        description: The foreign key for fct_sales and dim_sales_person.
      - name: promotion_key
        description: The foreign key for fct_sales and dim_promotion.
      - name: date_key
        description: The foreign key for fct_sales and dim_date.
      - name: net_unit_price
        description: Net unit price.
        tests:
          - not_null
      - name: regular_unit_price
        description: Regular unit price.
        tests:
          - not_null
      - name: line_profit
        description: Line profit.
        tests:
          - not_null
      - name: quantity
        description: Quantity.
        tests:
          - not_null
      - name: discount_unit_price
        description: Discount unit price.
        tests:
          - not_null
      - name: unit_profit
        description: Unit profix.
        tests:
          - not_null
      - name: unit_cost
        description: Unit cost.
        tests:
          - not_null
      - name: gross_revenue
        description: Gross revenue.
        tests:
          - not_null
      - name: net_revenue
        description: Net revenue.
        tests:
          - not_null
      - name: cost_amount
        description: Cost amount.
        tests:
          - not_null
      - name: gross_profit
        description: Gross profit.
        tests:
          - not_null
      - name: net_profit
        description: Net profit.
        tests:
          - not_null
