version: 2

models:
  - name: location
    description: All location data from staging.
    columns:
      - name: city_id
        description: The primary key for location.
        tests:
          - unique
          - not_null
      - name: state_province_id
        description: The primary key for location.
        tests:
          - not_null
      - name: country_id
        description: The primary key for location.
        tests:
          - not_null
      - name: city_name
        description: City name.
        tests:
          - not_null
      - name: state_province_name
        description: State province name.
        tests:
          - not_null
      - name: country_name
        description: Country name.
        tests:
          - not_null
